name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: blog/.vitepress/dist
