name: Build

on:
  push:
    branches:
      - dev
      - test-ci
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm i

      - name: Build
        run: pnpm build

      # - run: "ls ${{ github.workspace}}/blog/.vitepress/dist"

      # - name: Deploy Github Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.TOKEN }}
      #     publish_dir: blog/dist

      # - name: Deploy Serve
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: "-rltgoDzvO"
      #     SOURCE: "blog/dist/"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
      #     EXCLUDE: "/node_modules/"

      - name: 部署到 CloudBase
        run: "npx tcb login --apiKeyId ${{secrets.CLOUDBASE_KEY}} --apiKey ${{secrets.CLOUDBASE_SECRET}} && npm run deploy"
